import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Bot, Code, ImageIcon, Mic, FileText, ScanText, Rocket } from "lucide-react";
import Link from "next/link";
import { Badge } from "../ui/badge";

const features = [
  {
    icon: ImageIcon,
    title: "Art Generator",
    description: "Unleash your creativity by turning text prompts into stunning, high-resolution AI-generated images.",
    href: "/generate",
    badge: "Free"
  },
  {
    icon: Bot,
    title: "AI Chatbot",
    description: "Engage in intelligent conversations with our advanced AI chatbot, ready to assist you 24/7.",
    href: "/chatbot",
    badge: "Premium"
  },
  {
    icon: Mic,
    title: "Voice Generator",
    description: "Convert any text into natural-sounding speech. Perfect for voiceovers, podcasts, and more.",
    href: "/voice-generator",
    badge: "Premium"
  },
  {
    icon: FileText,
    title: "Smart Summarizer",
    description: "Save time by generating concise and accurate summaries of long articles, documents, or texts.",
    href: "/summarizer",
     badge: "Premium"
  },
  {
    icon: ScanText,
    title: "AI Detector",
    description: "Analyze text to determine whether it was written by a human or generated by an AI model.",
    href: "/ai-detector",
     badge: "Premium"
  },
  {
    icon: Code,
    title: "Auto-Coder Tool",
    description: "Describe your programming needs and get functional code snippets generated in seconds.",
    href: "/auto-coder",
     badge: "Premium"
  },
];

const AllFeaturesSection = () => {
  return (
    <section id="features" className="w-full">
      <div className="container mx-auto px-4">
        <div className="text-center mb-12">
            <h2 className="text-4xl md:text-5xl font-bold mb-4">Explore Our AI Toolkit</h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            A suite of powerful, next-generation AI tools designed to amplify your creativity and productivity.
            </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature) => {
            const Icon = feature.icon;
            return (
                <Link href={feature.href} key={feature.title} className="block group">
                    <Card 
                        className="h-full overflow-hidden transition-all duration-300 hover:shadow-lg hover:-translate-y-2 hover:border-primary"
                    >
                        <CardHeader>
                            <div className="flex items-start justify-between">
                                <div className="p-3 rounded-lg bg-secondary">
                                    <Icon className="h-6 w-6 text-primary" />
                                </div>
                                {feature.badge && <Badge variant={feature.badge === 'Free' ? 'secondary' : 'default'}>{feature.badge}</Badge>}
                            </div>
                            <CardTitle className="text-xl pt-4">{feature.title}</CardTitle>
                        </CardHeader>
                        <CardContent>
                            <p className="text-muted-foreground">{feature.description}</p>
                        </CardContent>
                    </Card>
                </Link>
            );
            })}
        </div>
      </div>
    </section>
  );
};

export default AllFeaturesSection;
